### ISSUE TITLE
AttributeError: 'XGBRegressor' object has no attribute 'get_fscore'

### ISSUE THREAD

**Issue by volker48** [ClimbsRocks/auto_ml#225]
Testing out auto_ml with XGBoost and ran into this issue. This is against a fresh clone of the XGBoost repository so it looks like their API changed.

`predictor.train(x_train, verbose=True, model_names=['XGBRegressor'])`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in _get_xgb_feat_importances(self, clf)
    890             # xgb.XGBClassifier.fit() or xgb.XGBRegressor().fit()
--> 891             fscore = clf.booster().get_fscore()
    892         except:

TypeError: 'str' object is not callable

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-37-eafdc24b187b> in <module>()
----> 1 predictor.train(x_train, verbose=True, model_names=['XGBRegressor'])

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in train(self, raw_training_data, user_input_func, optimize_final_model, write_gs_param_results_to_file, perform_feature_selection, verbose, X_test, y_test, ml_for_analytics, take_log_of_y, model_names, perform_feature_scaling, calibrate_final_model, _scorer, scoring, verify_features, training_params, grid_search_params, compare_all_models, cv, feature_learning, fl_data)
    469 
    470         # This is our main logic for how we train the final model
--> 471         self.trained_final_model = self.train_ml_estimator(estimator_names, self._scorer, X_df, y)
    472 
    473         # Calibrate the probability predictions from our final model

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning)
    672         # Use Case 1: Super straightforward: just train a single, non-optimized model
    673         if len(estimator_names) == 1 and self.optimize_final_model != True:
--> 674             trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning)
    675 
    676         # Use Case 2: Compare a bunch of models, but don't optimize any of them

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in fit_single_pipeline(self, X_df, y, model_name, feature_learning)
    554 
    555         self.trained_final_model = ppl
--> 556         self.print_results(model_name)
    557 
    558         return ppl

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in print_results(self, model_name)
    578 
    579         elif self.ml_for_analytics and model_name in ['RandomForestClassifier', 'RandomForestRegressor', 'XGBClassifier', 'XGBRegressor', 'GradientBoostingRegressor', 'GradientBoostingClassifier', 'LGBMRegressor', 'LGBMClassifier']:
--> 580             self._print_ml_analytics_results_random_forest()
    581 
    582 

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in _print_ml_analytics_results_random_forest(self)
    938         # XGB's Classifier has a proper .feature_importances_ property, while the XGBRegressor does not.
    939         if final_model_obj.model_name in ['XGBRegressor', 'XGBClassifier']:
--> 940             self._get_xgb_feat_importances(final_model_obj.model)
    941 
    942         else:

/home/ubuntu/venv/lib/python3.5/site-packages/auto_ml/predictor.py in _get_xgb_feat_importances(self, clf)
    893             # Handles case when clf has been created by calling xgb.train.
    894             # Thus, clf is an instance of xgb.Booster.
--> 895             fscore = clf.get_fscore()
    896 
    897         trained_feature_names = self._get_trained_feature_names()

AttributeError: 'XGBRegressor' object has no attribute 'get_fscore'
```

**Comment by ClimbsRocks** [comment]
Ugh, bummer. Thanks for letting me know! I'll ship a hotfix shortly to just avoid getting feature_importances for xgboost for now so it doesn't error out. The full fix will take a bit longer after that since I'm heading out on an out-of-wifi-range trip this weekend. 

I appreciate the bug report!

**Comment by volker48** [comment]
No problem. I did confirm its an issue in the tip of their master branch. I checked out the tag v0.60, reinstalled into my virtual environment, and then it worked fine.

**Comment by ClimbsRocks** [comment]
Eh, it's actually a pretty easy fix. I built this functionality while their `.feature_importances_` attribute was still not as functional as I needed. Turns out it gets us exactly what we need now, and is easier to use, while being less brittle. 

It also gave me an excuse to go in and fix that other bug you encountered. Still a bit befuddled where that one's coming from, but the symptom at least was pretty easy to fix. Waiting on CI to validate nothing accidentally got messed up, but the changes are in master, and assuming tests pass, I'll be pushing a new version to PyPi shortly!

**Comment by ClimbsRocks** [comment]
Also fixed in the latest v2.1.8 pip release. Thanks for letting me know!

**Comment by samuelcwl** [comment]
Ran into a similar issue against the latest install of py-xgboost on Python 3.5:

`py-xgboost                0.60            py35np112h1606666_0 `

Is this an issue with their Python 3.5 build / should I upgrade to Python 3.6?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in _print_ml_analytics_results_random_forest(self, trained_model_for_analytics, feature_responses)
   1293         try:
-> 1294             trained_feature_importances = final_model_obj.model.feature_importances_
   1295         except AttributeError as e:

AttributeError: 'XGBRegressor' object has no attribute 'feature_importances_'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-8-66663a216d46> in <module>()
      1 start_time = time.time()
      2 ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)
----> 3 ml_predictor.train(df_train, model_names=['XGBRegressor'])

/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in train(self, raw_training_data, user_input_func, optimize_final_model, write_gs_param_results_to_file, perform_feature_selection, verbose, X_test, y_test, ml_for_analytics, take_log_of_y, model_names, perform_feature_scaling, calibrate_final_model, _scorer, scoring, verify_features, training_params, grid_search_params, compare_all_models, cv, feature_learning, fl_data, train_uncertainty_model, uncertainty_data, uncertainty_delta, uncertainty_delta_units, calibrate_uncertainty, uncertainty_calibration_settings, uncertainty_calibration_data, uncertainty_delta_direction, advanced_analytics, analytics_config, prediction_intervals, predict_intervals)
    564 
    565         # This is our main logic for how we train the final model
--> 566         self.trained_final_model = self.train_ml_estimator(estimator_names, self._scorer, X_df, y)
    567 
    568         if self.need_to_train_uncertainty_model == True:

/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in train_ml_estimator(self, estimator_names, scoring, X_df, y, feature_learning, prediction_interval)
    991         # Use Case 1: Super straightforward: just train a single, non-optimized model
    992         elif len(estimator_names) == 1 and self.optimize_final_model != True:
--> 993             trained_final_model = self.fit_single_pipeline(X_df, y, estimator_names[0], feature_learning=feature_learning, prediction_interval=False)
    994 
    995         # Use Case 2: Compare a bunch of models, but don't optimize any of them

/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in fit_single_pipeline(self, X_df, y, model_name, feature_learning, prediction_interval)
    768 
    769         # self.trained_final_model = ppl
--> 770         self.print_results(model_name, ppl, X_df, y)
    771 
    772         return ppl

/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in print_results(self, model_name, model, X, y)
    886 
    887         elif self.ml_for_analytics and model_name in ['RandomForestClassifier', 'RandomForestRegressor', 'XGBClassifier', 'XGBRegressor', 'GradientBoostingRegressor', 'GradientBoostingClassifier', 'LGBMRegressor', 'LGBMClassifier', 'CatBoostRegressor', 'CatBoostClassifier']:
--> 888             self._print_ml_analytics_results_random_forest(model, feature_responses)
    889 
    890         else:

/anaconda/envs/python35/lib/python3.5/site-packages/auto_ml/predictor.py in _print_ml_analytics_results_random_forest(self, trained_model_for_analytics, feature_responses)
   1295         except AttributeError as e:
   1296             # There was a version of LightGBM that had this misnamed to miss the "s" at the end
-> 1297             trained_feature_importances = final_model_obj.model.feature_importance_
   1298 
   1299         feature_infos = zip(trained_feature_names, trained_feature_importances)

AttributeError: 'XGBRegressor' object has no attribute 'feature_importance_'
```

**Comment by samuelcwl** [comment]
Update: Used latest `xgboost` pip build as follows:

`xgboost                   0.6a2                     <pip>`

But error is still being thrown. Perhaps related to #232 ?

**Comment by ClimbsRocks** [comment]
yep! as we noted in that other thread, xgboost hasn't upgraded their pypi distribution in a while, despite making a host of changes in their master branch. i opted to go with support for their master branch where they've got the latest changes, rather than the outdated pypi distribution. 

so you can install from github (they should have some pretty good instructions to follow), and it should all work fine. 

or, i've switched over to using microsoft's lightgbm instead. it installs with an easy `pip install lightgbm` (though if you're on a mac, you may also need to update a compiler with homebrew: `brew upgrade gcc` too). it also runs faster, and achieves similar accuracy.

**Comment by cen8303** [comment]
hello, @volker48 , I also met the problem "TypeError: 'str' object is not callable" with xgboost 0.71, do you know how to where the problem is? Thanks a lot~

**Comment by sushant-singh01** [comment]
Hi, I encountered a similar issue when trying to ml_predictor.print_training_summary(ml_predictor.gs_param_file_name). Any clue?

```
The best CV score from our hyperparameter search (by default averaging across k-fold CV) for TIMESTP_ARR is:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-96-0ae89b0d17c9> in <module>
----> 1 ml_predictor.print_training_summary(ml_predictor.gs_param_file_name)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\automl-2.9.9-py3.6.egg\auto_ml\predictor.py in print_training_summary(self, gs)
   1630         if self.took_log_of_y:
   1631             print('    Note that this score is calculated using the natural logs of the y values.')
-> 1632         print(gs.best_score_)
   1633         print('The best params were')
   1634 

AttributeError: 'str' object has no attribute 'best_score_'
```
@ClimbsRocks
